name: Build
on:
  pull_request:
    branches:
      - main

jobs:

  build:
    strategy:
      max-parallel: 2
      matrix:
        node: [16, 18]
    name: Test on Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    env:
      MOMENTO_API_KEY: ${{ secrets.ALPHA_TEST_AUTH_TOKEN }}

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install dependencies
        run: |
          npm ci
          node -v
          npm ls --all

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
